version: "2.7"

server:
  command: "php public/index.php"
  env:
    - XDEBUG_SESSION: "1"

rpc:
  listen: tcp://127.0.0.1:6001

http:
  address: 0.0.0.0:8080
  middleware: [ "static", "gzip" ]
  uploads:
    forbid: [ ".php", ".exe", ".bat" ]
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]
  pool:
    num_workers: 2
    debug: false

logs:
  mode: development
  channels:
    http:
      level: debug # Log all http requests, set to info to disable
    server:
      level: info # Everything written to worker stderr is logged
      mode: raw
    metrics:
      level: debug

reload:
  enabled: true
  interval: 2s
  patterns: [".php", ".yaml"]
  services:
    http:
      dirs: ["."]
      patterns: [ ".php", ".yaml" ]
      ignore: [ "vendor", "var", ".make", "migrations" ]
      recursive: true

metrics:
  address: "0.0.0.0:9180"
  collect:
    app_load_articles_duration:
      type: gauge
      help: "Duration of load articles query"
    app_error_rate:
      type: counter
      help: "Error counter"
